services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.${DJANGO_ENV:-local}
  django-web:
    build: .
    container_name: conectora
    depends_on:
      - db
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.${DJANGO_ENV:-local}

  celery-worker:
    build: .
    depends_on:
      - db
    env_file:
      - .env.${DJANGO_ENV:-local}
    command: ["/app/entrypoint.worker.sh"]

volumes:
  postgres_data:






