# Generated by Django 5.2 on 2025-07-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_custom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicToken',
        ),
    ]
