# Generated by Django 5.2 on 2025-09-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_uploadbatch_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bootsrapped',
            field=models.BooleanField(default=False),
        ),
    ]
