# Generated by Django 5.2 on 2025-09-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_bootsrapped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_bootsrapped',
            new_name='is_bootstrapped',
        ),
    ]
