# Generated by Django 5.2 on 2025-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_is_bootsrapped_customuser_is_bootstrapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=12),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['batch', 'status'], name='users_uploa_batch_i_6f8a38_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['status', 'error_code'], name='users_uploa_status_5f64ef_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['created_at'], name='users_uploa_created_643a7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadfile',
            constraint=models.UniqueConstraint(fields=('batch', 'number_file'), name='uniq_batch_numberfile'),
        ),
    ]
