# Generated by Django 5.2 on 2025-07-29 13:58

import apps.developers.models
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_magictoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('consent_promotional_use', models.BooleanField(blank=True, null=True)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('cv_file', models.FileField(upload_to='resumes/')),
                ('cv_raw_text', models.TextField(blank=True, null=True)),
                ('university_education', models.JSONField(blank=True, default=None, null=True)),
                ('education_certificates', models.JSONField(blank=True, default=None, null=True)),
                ('relevant_years_of_experience', models.IntegerField(blank=True, null=True)),
                ('experience', models.JSONField(blank=True, default=None, null=True)),
                ('projects', models.JSONField(blank=True, default=None, null=True)),
                ('volunteering', models.JSONField(blank=True, default=None, null=True)),
                ('interests', models.JSONField(blank=True, default=None, null=True)),
                ('languages_spoken', models.JSONField(blank=True, default=None, null=True)),
                ('programming_languages', models.JSONField(blank=True, default=None, null=True)),
                ('frameworks_libraries', models.JSONField(blank=True, default=None, null=True)),
                ('architectures_patterns', models.JSONField(blank=True, default=None, null=True)),
                ('tools_version_control', models.JSONField(blank=True, default=None, null=True)),
                ('databases', models.JSONField(blank=True, default=None, null=True)),
                ('cloud_platforms', models.JSONField(blank=True, default=None, null=True)),
                ('testing_qa', models.JSONField(blank=True, default=None, null=True)),
                ('devops_ci_cd', models.JSONField(blank=True, default=None, null=True)),
                ('containerization', models.JSONField(blank=True, default=None, null=True)),
                ('data_skills', models.JSONField(blank=True, default=None, null=True)),
                ('frontend_technologies', models.JSONField(blank=True, default=None, null=True)),
                ('mobile_development', models.JSONField(blank=True, default=None, null=True)),
                ('apis_integrations', models.JSONField(blank=True, default=None, null=True)),
                ('security', models.JSONField(blank=True, default=None, null=True)),
                ('agile_pm', models.JSONField(blank=True, default=None, null=True)),
                ('operating_systems', models.JSONField(blank=True, default=None, null=True)),
                ('main_developer_role', models.CharField(blank=True, max_length=100, null=True)),
                ('country_living_in', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('telephone_number', models.CharField(blank=True, max_length=15, validators=[apps.developers.models.validate_phone])),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('indicative_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('schema_version', models.CharField(default='v1', max_length=20)),
            ],
        ),
    ]
