# Generated by Django 5.2 on 2025-08-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='has_cv',
            field=models.BooleanField(default=False),
        ),
    ]
