# Generated by Django 5.2 on 2025-08-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developerprofile_has_cv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='developerprofile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
