# Generated by Django 5.2 on 2025-09-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_alter_developerprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerprofile',
            old_name='cv_original_name',
            new_name='cv_name',
        ),
    ]
