# Generated by Django 5.2 on 2025-09-29 08:31

import apps.developers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_rename_cv_original_name_developerprofile_cv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='cv_file',
            field=models.FileField(blank=True, storage=apps.developers.models.CVStorage(), upload_to=apps.developers.models.cv_upload_path),
        ),
    ]
