# Generated by Django 5.2 on 2025-10-01 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_alter_developerprofile_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
