# Generated by Django 5.1.7 on 2025-04-21 16:48

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('summary', models.TextField(blank=True)),
                ('bachelor', models.CharField(max_length=255, validators=[users.models.validate_string])),
                ('university_bachelor', models.CharField(max_length=255, validators=[users.models.validate_string])),
                ('master', models.CharField(max_length=255, validators=[users.models.validate_string])),
                ('university_master', models.CharField(max_length=255, validators=[users.models.validate_string])),
                ('years_of_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), users.models.validate_integer])),
                ('skills', models.TextField(max_length=1000)),
                ('projects', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, default='profilepic.jpg', null=True, upload_to='profile_pictures')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
