# Generated by Django 5.2 on 2025-05-14 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university_education', models.JSONField(blank=True, default=None, null=True)),
                ('education_certificates', models.JSONField(blank=True, default=None, null=True)),
                ('experience', models.JSONField(blank=True, default=None, null=True)),
                ('skills', models.JSONField(blank=True, default=None, null=True)),
                ('projects', models.JSONField(blank=True, default=None, null=True)),
                ('interests', models.JSONField(blank=True, default=None, null=True)),
                ('volunteering', models.JSONField(blank=True, default=None, null=True)),
                ('languages', models.JSONField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
            ],
        ),
    ] 