# Generated by Django 5.2 on 2025-05-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_promotional_use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ] 