# Generated by Django 5.2 on 2025-05-30 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('freelancers', '0002_profile_consent_given_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('consent_promotional_use', models.BooleanField(blank=True, null=True)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('university_education', models.JSONField(blank=True, default=None, null=True)),
                ('education_certificates', models.JSONField(blank=True, default=None, null=True)),
                ('experience', models.JSONField(blank=True, default=None, null=True)),
                ('skills', models.JSONField(blank=True, default=None, null=True)),
                ('projects', models.JSONField(blank=True, default=None, null=True)),
                ('interests', models.JSONField(blank=True, default=None, null=True)),
                ('volunteering', models.JSONField(blank=True, default=None, null=True)),
                ('languages', models.JSONField(blank=True, default=None, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
