# Generated by Django 5.2 on 2025-09-22 08:14

import apps.developers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0008_uploadfile_error_message_uploadfile_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clientprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_number', models.CharField(blank=True, max_length=15, validators=[apps.developers.models.validate_phone])),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3, null=True)),
            ],
        ),
    ]
