# Generated by Django 5.2 on 2025-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='role_in_company',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
