# Generated by Django 5.2 on 2025-09-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_role_in_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clientproject', serialize=False, to='clients.clientprofile')),
                ('initial_ask', models.JSONField(blank=True)),
                ('proposal_draft', models.JSONField(blank=True)),
                ('tech_stack_draft', models.JSONField(blank=True)),
                ('potential_candidates', models.JSONField(blank=True)),
                ('selected_candidates', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='active_projects',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='completed_projects',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='search_limit',
            field=models.PositiveIntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='total_candidates_matched',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='role_in_company',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
