# Generated by Django 5.2 on 2025-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_project_id_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='active_projects',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='completed_projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='initial_ask',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='number_of_projects',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='intake_requirements',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_intake',
            field=models.CharField(choices=[('intake_requirements', 'Requirements received'), ('proposal_draft', 'AI-made proposal draft'), ('tech_stack_draft', 'Created a tech stack draft'), ('potential_candidates', 'Searched for potential candidates'), ('selected_candidates', 'Selected final candidates')], default='intake_requirements', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status_project',
            field=models.CharField(choices=[('ai_intake', 'AI Intake'), ('presale', 'Presale'), ('contract_signed', 'Contract signed'), ('cancelled_contract', 'Cancelled contract'), ('completed', 'Completed')], default='ai_intake', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='potential_candidates',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal_draft',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='selected_candidates',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack_draft',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
