# Generated by Django 5.2 on 2025-09-23 22:46

import apps.clients.models
import apps.developers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_clientprofile_active_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_description', models.TextField(blank=True, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('end_user', models.TextField(blank=True, null=True)),
                ('end_goal', models.TextField(blank=True, null=True)),
                ('must_features', models.TextField(blank=True, null=True)),
                ('required_workflows', models.TextField(blank=True, null=True)),
                ('must_not_do', models.TextField(blank=True, null=True)),
                ('recommended_stack', models.TextField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='clients.project')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.developers.models.CVStorage(), upload_to=apps.clients.models.intake_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.intake')),
            ],
        ),
    ]
