# Generated by Django 5.2 on 2025-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_intake_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='clients.project'),
        ),
    ]
