# Generated by Django 5.2 on 2025-09-26 06:45

import apps.clients.models
import apps.developers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_intake_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status_intake',
        ),
        migrations.AddField(
            model_name='intake',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='intake',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intake',
            name='status',
            field=models.CharField(choices=[('intake_requirements', 'Requirements received'), ('proposal_draft', 'AI-made proposal draft'), ('tech_stack_draft', 'Created a tech stack draft'), ('potential_candidates', 'Searched for potential candidates'), ('selected_candidates', 'Selected final candidates')], default='intake_requirements', max_length=20),
        ),
        migrations.AlterField(
            model_name='intake',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_intake', to='clients.project'),
        ),
        migrations.CreateModel(
            name='IntakeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.developers.models.CVStorage(), upload_to=apps.clients.models.intake_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakedocuments', to='clients.intake')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
