# Generated by Django 5.2 on 2025-10-01 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_rename_potential_candidates_project_potential_candidates_per_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='intake_requirements',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='processing_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intakedocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='matching_status',
            field=models.CharField(choices=[('intake_requirements', 'Requirements received'), ('proposal_draft', 'AI-made proposal draft'), ('tech_stack_draft', 'Created a tech stack draft'), ('team_recommendation', 'Created a team recommendation'), ('potential_candidates', 'Searched for potential candidates'), ('selected_candidates', 'Selected final candidates')], default='intake_requirements', max_length=40),
        ),
    ]
