# Generated by Django 5.2 on 2025-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_project_intake_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='search_limit',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
