# Generated by Django 5.2 on 2025-10-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clientprofile_search_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='number_of_projects',
        ),
    ]
